In [1]:
# glob 用法
import glob, os
import pandas as pd
fnames = glob.glob("chinese_news_trans/*/*.txt")
datas= {
    "content": [],
    "target": []
}
for fn in fnames:
    with open(fn, "r", encoding="utf-8") as f:
        content = f.read()
        datas["content"].append(content)
        dn = os.path.split(fn)[0]
        dn = os.path.split(dn)[-1]
        datas["target"].append(dn)
train_df = pd.DataFrame(datas)
train_df
#正確率, 混亂矩陣, 載入新的新聞

                                                content target
0     【 日  期 】19960104\n【 版  號 】1\n【 標  題 】合巢蕪高速公路巢蕪...     交通
1     【 日  期 】19960226\n【 版  號 】5\n【 標  題 】我首臺載人磁懸浮列...     交通
2                大秦鐵路萬噸列車試運成功\n新華社北京５月２４日電（通訊員李忠民）大秦...     交通
3                遼寧省檯安縣村村都通柏油路鄉村公路建設全國數第\n一\n    (4)...     交通
4                北京—烏蘭巴托—莫斯料３／４次國際旅客列車通車\n３０週年\n    ...     交通
...                                                 ...    ...
2632             馬玉芹破女子４００米跑全國青年紀錄\n新華社鞍山５月１０日電（通訊員王...     體育
2633             國際奧委會中國臺北委員吳經國訪問北京\n新華社北京５月１０日電記者《中...     體育
2634             亞奧理事會３９個成員組織全部以書面形式確認參加\n第十一屆亞運會\n ...     體育
2635             世界盃乒乓球團體賽男子團體採用新賽制\n新華社北京５月１０日電（記者樑...     體育
2636             登頂隊員簡介\n新華社珠穆朗瑪峰５月１０日電登頂隊員簡介\n     ...     體育

[2637 rows x 2 columns]

In [2]:
fnames = glob.glob("chinese_news_test/*/*.txt")
datas= {
    "content": [],
    "target": []
}
for fn in fnames:
    with open(fn, "r", encoding="utf-8") as f:
        content = f.read()
        datas["content"].append(content)
        dn = os.path.split(fn)[0]
        dn = os.path.split(dn)[-1]
        datas["target"].append(dn)
test_df = pd.DataFrame(datas)
test_df

                                               content target
0    日月光華 -- Traffic_Info精華區文章閱讀\n-----------------...     交通
1    日月光華 -- Traffic_Info精華區文章閱讀\n-----------------...     交通
2    日月光華 -- Traffic_Info精華區文章閱讀\n-----------------...     交通
3    三趟火車停開 乘客可全額退票 \n瀏覽次數：1180 \n    昨日，來自鐵路部門的消息說...     交通
4    日月光華 -- Traffic_Info精華區文章閱讀\n-----------------...     交通
..                                                 ...    ...
96   最優秀選手無緣亞運會健美賽\n \n　 \n    健美在亞洲運動會上是“新生兒”——韓國釜...     體育
97    \n各國記者眼中的羽毛球世錦賽\n \n\n-----------------------...     體育
98   \n友好運動會第五天 東道主選手大顯神威\n2001年09月03日02:51:40 新華社 ...     體育
99   不靠技術比運氣\n\n　　第二屆奧運會在巴黎舉行，同時這裡也正在舉行國際博覽會，東道主把一些...     體育
100  帆 板 運 動 簡 介（二）\n\n　　我國在79年由國家體委青島航海運動學校成功試製出第一...     體育

[101 rows x 2 columns]

In [3]:
import jieba
#載入大辭典
jieba.set_dictionary("dict.txt.big")
def newscut(s):
    s = " ".join(jieba.cut(s))
    s = s.replace("\r", "").replace("\n", "")
    return s
# pandas表格: 多行多列 DataFrame, 單行單列 Series, 這邊是用 Series的 apply(功能名字) ->打名字就好, 之後會自己帶 
x_train = train_df["content"].apply(newscut)
x_test = test_df["content"].apply(newscut)
print(x_train)
print(x_test)

Building prefix dict from D:\dict.txt.big ...
Loading model from cache C:\Users\niel\AppData\Local\Temp\jieba.ub18b883c92529549e6ceff6bcd158ca1.cache
Loading model cost 3.280 seconds.
Prefix dict has been built successfully.

0       【   日     期   】 19960104  【   版     號   】 1  【...
1       【   日     期   】 19960226  【   版     號   】 5  【...
2                             大秦鐵路 萬噸 列車 試運 成功  新華社 北京...
3                             遼寧省 檯安縣 村村 都 通 柏油路 鄉村 公路...
4                             北京 — 烏蘭巴托 — 莫斯料 ３ ／ ４ 次 ...
                              ...
2632                          馬玉芹 破 女子 ４ ０ ０ 米 跑 全國 青年...
2633                          國際奧委會 中國臺北 委員 吳經國 訪問 北京 ...
2634                          亞奧 理事會 ３ ９ 個 成員 組織 全部 以 ...
2635                          世界盃 乒乓球 團體賽 男子 團體 採用 新 賽...
2636                          登頂 隊員 簡介  新華社 珠穆朗瑪 峰 ５ 月...
Name: content, Length: 2637, dtype: object
0      日月 光華   --   Traffic _ Info 精華區 文章 閱讀  -------...
1      日月 光華   --   Traffic _ Info 精華區 文章 閱讀  -------...
2      日月 光華   --   Traffic _ Info 精華區 文章 閱讀  -------...
3      三趟 火車 停開   乘客 可 全額 退票    瀏覽 次數 ： 1180         ...
4      日月 光華   --   Traffic _ Info 精華區 文章 閱讀  -------...
                             ...
96     最 優秀 選手 無緣 亞運會 健美 賽     　            健美 在 亞洲 運...
97        各國 記者 眼中 的 羽毛球 世錦賽      -------------------...
98      友好 運動會 第五天   東道主 選手 大顯神威  2001 年 09 月 03 日 02...
99     不靠 技術 比 運氣   　 　 第二屆 奧運會 在 巴黎 舉行 ， 同時 這裡 也 正在 ...
100    帆   板   運   動   簡   介 （ 二 ）   　 　 我國 在 79 年 由 ...
Name: content, Length: 101, dtype: object

In [4]:
#將target轉換成數字
u = train_df["target"].unique()
trans = {name: i for i, name in enumerate(u)}
reverse_trans = {i:name for name, i in trans.items()}
print(trans)
print(reverse_trans)
y_train = train_df["target"].replace(trans)
y_test = test_df["target"].replace(trans)
y_test

{'交通': 0, '政治': 1, '教育': 2, '環境': 3, '經濟': 4, '藝術': 5, '計算機': 6, '軍事': 7, '醫藥': 8, '體育': 9}
{0: '交通', 1: '政治', 2: '教育', 3: '環境', 4: '經濟', 5: '藝術', 6: '計算機', 7: '軍事', 8: '醫藥', 9: '體育'}

0      0
1      0
2      0
3      0
4      0
      ..
96     9
97     9
98     9
99     9
100    9
Name: target, Length: 101, dtype: int64

In [5]:
#把每一個詞轉換成數量, 每一個詞出現幾遍
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
x_train_vec = vec.fit_transform(x_train)
x_test_vec = vec.transform(x_test)

In [6]:
#單純貝式運算
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(x_train_vec, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [7]:
#預測, 算機率
from sklearn.metrics import accuracy_score
pre = clf.predict(x_test_vec)
print("正確率:", accuracy_score(y_test, pre))

正確率: 1.0

In [8]:
#混淆矩陣
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test, pre)
c = ["{}(預測)".format(name) for name in u]
i = ["{}(原本)".format(name) for name in u]
pd.DataFrame(mat, columns=c, index=i)

,交通(預測),政治(預測),教育(預測),環境(預測),經濟(預測),藝術(預測),計算機(預測),軍事(預測),醫藥(預測),體育(預測)
交通(原本),10,0,0,0,0,0,0,0,0,0
政治(原本),0,11,0,0,0,0,0,0,0,0
教育(原本),0,0,10,0,0,0,0,0,0,0
環境(原本),0,0,0,10,0,0,0,0,0,0
經濟(原本),0,0,0,0,10,0,0,0,0,0
藝術(原本),0,0,0,0,0,10,0,0,0,0
計算機(原本),0,0,0,0,0,0,10,0,0,0
軍事(原本),0,0,0,0,0,0,0,10,0,0
醫藥(原本),0,0,0,0,0,0,0,0,10,0
體育(原本),0,0,0,0,0,0,0,0,0,10

In [ ]:
#回顧
p =input("輸入新聞:")
#注意[], [第一個新聞, 第二個新聞]
p = vec.transform([newscut(p)])
#注意[], [第一個答案, 第二個答案]
ans = clf.predict(p)[0]
print("答案應該是:", reverse_trans[ans])
clf.predict_proba(p)[0]
for n, prob in sorted(zip(u, proba), key=lambda x:[1], reverse=True):
    print(n, "的機率是:", prob* 100%, "%")

In [ ]:
#排序, 本來應該def, 直接用 lambda處理
def s(x):
    return x[1]
sorted(zip(u, proba), key=lambda x:x[1], reverse=True)

In [ ]:
#zip如果有兩個群集, 會把對應位子的東西合起來, zip()
list(zip[1, 2, 3], [4, 5, 6], [7, 8, 9, 10])